import Navigation from "./components/navigation";
import "./globals.css";
import { Inter } from "next/font/google";
import { Footer } from "./Testing"
import SeesionWrapper from "./components/session/sessionWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SeesionWrapper>
        <Navigation />
        {children}
        <Footer />
        </SeesionWrapper>
      </body>
    </html>
  );
}